[tool.poetry]
name = "notebooks"
version = "0.1.0"
description = ""
authors = ["satoooh <bighope.lumiere0916@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
ipykernel = "^6.21.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
